package com.chromascape.utils.core.input.mouse;

import com.chromascape.base.BaseScript;
import com.chromascape.utils.core.input.remoteinput.MouseButton;
import com.chromascape.utils.core.input.remoteinput.RemoteInput;
import com.chromascape.utils.core.state.BotState;
import com.chromascape.utils.core.state.StateManager;
import com.chromascape.utils.core.statistics.StatisticsManager;
import java.awt.Point;
import java.awt.Rectangle;
import java.util.Objects;
import java.util.Random;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicReference;

/**
 * High level abstraction for a user to handle mouse IO through the {@link
 * com.chromascape.controller.Controller}. Orchestrator of both the mouse movement physics
 * calculation and dispatching of IO via the JNA layer. Uses a producer -> consumer threading model
 * to prevent a mouse movement from lagging if the IO fails or stutters. Provides IO capabilities
 * such as mouse movement, clicking, and holding of {@link MouseButton}s.
 */
public class VirtualMouseUtils {

  /** The current virtual mouse position. */
  private Point currentPosition;

  /** Interface for injecting low-level mouse events independently of system mouse. */
  private final RemoteInput input;

  /** Humanised mouse movement service. */
  private final WindMouse windMouse;

  private final Random random = new Random();

  /** The latest point generated by the physics engine, waiting to be consumed by input. */
  private final AtomicReference<Point> pendingInputPoint = new AtomicReference<>();

  /** Flag to indicate if the virtual mouse is currently performing a movement path. */
  private final AtomicBoolean isMoving = new AtomicBoolean(false);

  /**
   * Lock object to ensure input is accessed by only one thread at a time.
   *
   * <p>Required because the underlying WebSocket/Connection in input is not thread-safe and cannot
   * handle simultaneous write operations.
   */
  private final Object inputLock = new Object();

  /**
   * Constructs the VMU class. Initialises the mouse overlay. Gives the mouse cursor a random start
   * position. Starts the input consumer thread.
   *
   * @param input A hardware RemoteInput capable object
   */
  public VirtualMouseUtils(RemoteInput input) {
    this.input = input;
    windMouse = new WindMouse();
    // Randomize starting position within the client window
    randomiseStartPos();
    // Initialize atomic reference to prevent null pointer in consumer
    pendingInputPoint.set(currentPosition);
    // Start the background Input Consumer thread
    startInputConsumerThread();
  }

  /** Starts the input consumer thread to prepare for IO. */
  private void startInputConsumerThread() {
    Thread inputConsumerThread = new Thread(this::consumeInputLoop, "VirtualMouse-Input-Consumer");
    inputConsumerThread.setDaemon(true); // Ensure thread dies when JVM shuts down
    inputConsumerThread.start();
  }

  /**
   * Randomises the start position of the cursor within the client's bounds. Only used at startup.
   * If the bot ran before and has a persisting cursor, it will default to that instead.
   */
  private void randomiseStartPos() {
    if (Objects.equals(input.getMousePosition(), new Point(0, 0))
        || input.getMousePosition() == null) {

      Rectangle bounds = input.getTargetDimensions();
      int startX = bounds.x + random.nextInt(bounds.width);
      int startY = bounds.y + random.nextInt(bounds.height);
      currentPosition = new Point(startX, startY);
    } else {
      currentPosition = input.getMousePosition();
    }
    currentPosition = input.getMousePosition();
    // Initialize atomic reference to prevent null pointer in consumer
    pendingInputPoint.set(currentPosition);
  }

  /**
   * Used alongside the producer thread to reliably move the mouse. While the flag is set to true,
   * consumes the latest snapshot of the mouse movement simulation and sends a synchronised call to
   * the IO layer to move the mouse. Discards duplicates.
   */
  private void consumeInputLoop() {
    Point lastSentPoint = null;

    while (true) {
      if (isMoving.get()) {
        // Practically final value, will not change during execution
        Point target = pendingInputPoint.get();

        // Only send input if the point is new
        if (target != null && !target.equals(lastSentPoint)) {
          synchronized (inputLock) {
            input.moveMouse(target);
          }
          lastSentPoint = target;
        }
      } else {
        // If not moving, sleep longer to save resources
        BaseScript.waitMillis(5);
      }
    }
  }

  /**
   * Intended to be called before IO execution. Checks whether the script has been stopped to
   * reliably prevent execution. Sets the bot state to acting and increments inputs for the web UI's
   * statistics.
   */
  private void prepareInput() {
    BaseScript.checkInterrupted();
    StateManager.setState(BotState.ACTING);
    StatisticsManager.incrementInputs();
  }

  /**
   * Moves the mouse to a target destination point onscreen at a given speed using a humanised mouse
   * movement algorithm.
   *
   * @param target The {@link Point} location to travel to
   * @param speed How fast the mouse should travel, "slow", "medium" or "fast"
   */
  public void moveTo(final Point target, final String speed) {
    prepareInput();

    // Flag start of movement for the Consumer thread
    isMoving.set(true);

    try {
      // WindMouse's physics loop will run on the current thread, producer
      // The hardware IO execution (plus overlay/current state) is the consumer thread
      windMouse.move(currentPosition, target, speed, this::moveMouseImpl);
    } finally {
      finaliseMovement(target);
    }
  }

  /**
   * Callback for the WindMouse algorithm, where it used to execute the mouse movement action. This
   * function only updates the state for the consumer thread, however serves as a nod to the source.
   *
   * @param p The point generated by WindMouse.
   */
  private void moveMouseImpl(Point p) {
    pendingInputPoint.set(p);
    currentPosition = p;
  }

  /**
   * Disables the flag for the consumer thread, signaling there is no more work to do. Forces the
   * destination point for the internal state, remote input, and overlay; to ensure scripts do not
   * fail.
   *
   * @param target The final mouse destination.
   */
  private void finaliseMovement(Point target) {
    // Movement finished.
    isMoving.set(false);
    // Force the final position update to ensure exact accuracy.
    currentPosition = target;
    pendingInputPoint.set(target);
    // Snap to final position to force script safety
    // synchronized to prevent race conditions with other IO
    synchronized (inputLock) {
      input.moveMouse(target);
    }
  }

  /**
   * Executes a mouse button press and release in a human-like fashion, given which button to press.
   * Synchronised as not to collide with other IO.
   *
   * @param button the mouse button to press
   */
  private void click(MouseButton button) {
    prepareInput();
    synchronized (inputLock) {
      input.holdMouse(button);
      BaseScript.waitRandomMillis(50, 80);
      input.releaseMouse(button);
    }
  }

  /** Left clicks at the current mouse position. */
  public void leftClick() {
    click(MouseButton.left);
  }

  /** Right clicks at the current mouse position. */
  public void rightClick() {
    click(MouseButton.right);
  }

  /** Middle clicks at the current mouse position. */
  public void middleClick() {
    click(MouseButton.middle);
  }

  /**
   * Holds down a Mouse button given which button to hold.
   *
   * @param button the {@link MouseButton} to hold.
   */
  public void holdMouseButton(MouseButton button) {
    prepareInput();
    synchronized (inputLock) {
      if (!input.isMouseHeld(button)) {
        input.holdMouse(button);
      }
    }
  }

  /**
   * Queries whether a {@link MouseButton} is currently being held.
   *
   * @param button The {@link MouseButton} to check
   * @return Whether it's currently being held
   */
  public boolean isMouseButtonHeld(MouseButton button) {
    return input.isMouseHeld(button);
  }

  /**
   * Releases a Mouse button given which button to release.
   *
   * @param button the {@link MouseButton} to release.
   */
  public void releaseMouseButton(MouseButton button) {
    prepareInput();
    synchronized (inputLock) {
      if (input.isMouseHeld(button)) {
        input.releaseMouse(button);
      }
    }
  }

  /**
   * Scrolls the mouse given the direction and amount. The mouse must have moved in the particular
   * session for scrolling to take effect.
   *
   * @param totalNotches Amount of notches to scroll
   * @param down true if scrolling down, false if scrolling up
   */
  public void scrollMouse(int totalNotches, boolean down) {
    int notchesSent = 0;
    int k = 1;

    int step = (int) Math.round(random.nextGaussian() * 0.6 + 6.0);

    while (notchesSent < totalNotches) {
      input.scrollMouse(down ? 1 : -1);
      notchesSent++;

      if (k % step == 0) {
        step = (int) Math.round(random.nextGaussian() * 0.6 + 6.0);
        BaseScript.waitRandomMillis(215, 410);
        k = 0;
      } else {
        BaseScript.waitRandomMillis(25, 46);
      }
      k++;
    }
  }
}
